version: "3.3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=memories
      - MYSQL_ROOT_PASSWORD=test123
    volumes:
      - memories-db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - memories

  minio:
    image: minio/minio:latest
    command: minio server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${BUCKET_ACCESS_ID}
      MINIO_ROOT_PASSWORD: ${BUCKET_SECRET_KEY}
    restart: always
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
    volumes:
      - minio-data:/data
    networks:
      - memories

  create-bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${BUCKET_ACCESS_ID} ${BUCKET_SECRET_KEY};
      /usr/bin/mc mb myminio/${BUCKET_NAME};
      "
    networks:
      - memories

networks:
  memories:

volumes:
  memories-db:
  minio-data:
